# ebnf for a calculator
digit           = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9';
number          = unary operator, (digit)+, ('.', (digit)+)?;
unary operator  = '+' | '-';
operator        = '+' | '-' | '*' | '/';
expression      = ( expression ) | (expression, operator, expression) | (number, operator, number);